### ISSUE TITLE
Why the attack acc of attack_script and inference.py is different?

### ISSUE THREAD

**Issue by cuge1995** [Wuziyi616/IF-Defense#1]

**Comment by Wuziyi616** [comment]
Thank you for your interest in our work! Yes, we also observe this in our experiments. There may be several possible reasons:

1. If you normalize the adversarially generated point clouds in the pre-processing of inference, the accuracy/attack success rate will change. This is because during the attack, none of the methods perform normalization of point clouds. So the generated point clouds may not center within a unit sphere, and a simple normalization can serve as a (weak) defense. In the paper, I report the accuracy output by the attack_scripts because this is the common practice in previous papers. Note that, I have tried their original TensorFlow implementations and this difference of accuracy/attack success rate still exists. Maybe future work about point cloud attacks should consider normalizing the point cloud during the attack.

2. For PointNet++ and PointConv, since the operations (FPS sampling, local points grouping) used in the networks involve randomness, the prediction results can vary slightly. I often observe a ~1% difference in accuracy even tested on the same point clouds using the same random seed. This may also cause the difference.

3. Regarding attack success rate, I observe that it is more unstable than model accuracy. After all, targeted attack requires more delicate perturbations compared to untargeted attack. And that is why point cloud defense papers often report accuracy after defense for evaluation.

Hope my answers can help!

**Comment by cuge1995** [comment]
I've noticed that the final success_num come from `success_num = (lower_bound > 0.).sum()` but not come from `success_num = (pred == target).sum().item()`, does this matter ?

**Comment by Wuziyi616** [comment]
Yes, you are right. ```lower_bound``` is updated in binary search. Generally speaking, if a point cloud is successfully attacked, the lower bound will be modified to a positive value, so ```success_num = (lower_bound > 0.).sum()``` should be valid. But if you change it to ```success_num = (pred == target).sum().item()```, you will get worse attack success rate.

**Comment by Wuziyi616** [comment]
Feel free to reopen this issue if you have further questions :)
