### ISSUE TITLE
How to perform defense

### ISSUE THREAD

**Issue by Daniel-xsy** [Wuziyi616/IF-Defense#12]
Thanks for your great work! I'm confused about when to implement the `SOR` or the `SRS` defense. I check several related works and find two settings:

#### Setting1
In the code of CVPR'22 [Shape-Invariant-Attack](https://github.com/shikiw/SI-Adv), they put the defense (e.g., `SOR`) in **BOTH** attack iteration and attack process. This can simulate settings where attackers get complete information of the model **AND** defense methods.

#### Setting2
I tried the situation where the attackers do not know the defense methods (e.g., don't use defense in the attack iterations). In this setting, the accuracy essentially increases, which is expected.

I re-implement the `drop-200` attack with the `SOR` defense under the above two settings. The adversarial accuracy of 1st setting is 46.1, which is close to your paper results (42.6). The result of the 2nd setting is 35.2.

I find you load adversarial points from files in [`defend_npz.py`](https://github.com/Wuziyi616/IF-Defense/blob/7be443d17fbc4454dda7e335ed91179a39faefd4/baselines/defend_npz.py), which seems to be the **Setting2**. I just wonder which setting you adopted in your paper. If you adopt **Setting2**, have you tried to test the performance of IF-Defense under **Setting1**, will the defense performance still be good?

**Comment by Wuziyi616** [comment]
Hi, thanks for your interest in our work. As you said, we adopted `setting2` (black-box attack) where the attacker doesn't know the defense method. This is partially because IF-Defense is non-differentiable (hard to calculate the gradient of the optimization process), so we cannot adopt `setting1` (white-box attach) against IF-Defense. Therefore, to perform a fair comparison, we test all the defense/attacks under `setting2`.

As described above, it's hard to test IF-Defense under `setting1`. Instead, I tried the so-called *gray-box attack* or *adaptative attack*, where the attacker has some knowledge of our defense method, and has special design to attack it. Please see our paper Section 4.2 `Adaptive attack` part for the results. Overall, the `Adaptive attack` indeed outperforms setting2 attack, but our defense accuracy is still okay.

**Comment by Wuziyi616** [comment]
Btw, I do implement the `drop-200` attack in this repo [here](https://github.com/Wuziyi616/IF-Defense/blob/main/baselines/attack/Saliency/Drop.py), which can reproduce the results reported in the paper.

**Comment by Daniel-xsy** [comment]
Get it, thanks for your kind reply!
