### ISSUE TITLE
Point cloud model classification accuracy decreases after hybrid training

### ISSUE THREAD

**Issue by jamesliu609** [Wuziyi616/IF-Defense#15]
Hello ziyi, I use the original point cloud to pass through our defense model and provide it to pointnet training, but the classification accuracy of the trained pointnet on the clean point cloud attack_data.npz processed by our defense is reduced. Why is this?

**Comment by Wuziyi616** [comment]
What do you mean by accuracy is reduced (the accuracy is lower compared to what)? Do you mean the accuracy of [trained pointnet on defended point cloud] is lower than [original pointnet on clean point cloud]? This is somewhat expected, because defense methods will inevitable distort point clouds a bit, thus degrading the performance. I guess as long as the degradation is not a lot (say, 2%), it is acceptable.

**Comment by jamesliu609** [comment]
Yes, we use the defense method on **_mn40_random2048.npz_** _to obtain **def_mn40.npz_** for hybrid training of pointnet, and then test pointnet against the attack-free point cloud data **_def_attack_data.npz_** after defense processing. Compared with the normally trained pointnet, the accuracy of the hybrid trained pointnet dropped by about 10%. This problem bothers me.

**Comment by Wuziyi616** [comment]
Hum, that's a lot. Did you only train on `def_attack_data.npz`, or did you train on a mix of `def_attack_data.npz` and `mn40_random2048.npz`? In my paper, I did mixed training, so that the model performance is high on both defended and clean point cloud.

Mix training is just when training the model, we randomly sample data from both sets in a batch.

**Comment by jamesliu609** [comment]
I trained on a mix of `def_attack_data.npz` and `mn40_random2048.npz`, but the model only performs well on clean data.

**Comment by Wuziyi616** [comment]
That's very weird. In my case I trained on both data, and it works well on both clean data and defended data (still slight drop in performance, but not a lot). Maybe your defended data are too different from the clean data, so there is domain gap, which makes the model hard to perform well in both cases. I suggest you check your defense method for this.

**Comment by jamesliu609** [comment]
Well, thank you for your patience in answering.
