### ISSUE TITLE
Could you please provide more details about training conv-o-net on modelnet40?

### ISSUE THREAD

**Issue by paulwong16** [Wuziyi616/IF-Defense#2]
e.g. how to create a dataset used in training convolutional occupancy networks.

thanks

**Comment by Wuziyi616** [comment]
Thank you for your interest in our work! The main part of our training code is adopted from [ONet](https://github.com/autonomousvision/occupancy_networks) and [ConvONet](https://github.com/autonomousvision/convolutional_occupancy_networks). They are well-written with good comments. I didn't change the network architectures/training schedules, just modify the dataset by adding rotation augmentation as described in the paper. I believe you can easily change them to ModelNet40. So I will briefly introduce something about creating the dataset.

The main scripts and codes are still adopted from ONet repo [here](https://github.com/autonomousvision/occupancy_networks#building-the-dataset). First, you need to download the original ModelNet40 dataset in the **Mesh** format from [here](https://modelnet.cs.princeton.edu/ModelNet40.zip). Then unpack it and run the scripts ```build.sh``` ONet repo provides. Finally run ```install.sh``` and you will get the processed ModelNet40 dataset which can be used for ONet/ConvONet training.

However, for me, I failed to run ```build.sh``` because I can't build ```mesh-fusion``` as described in his README. Then I discovered [this issue](https://github.com/autonomousvision/occupancy_networks/issues/27) saying that it is not necessary to build it. Alternatively, I use [Manifold](https://github.com/autonomousvision/occupancy_networks/issues/27#issuecomment-543060210) to convert meshes in ModelNet40 to be watertight. Additionally, in my task, I only need point clouds and their occupancy values as training data. So I deleted all the processing steps used to generate Voxel/Rendering images. Finally I successfully install the dataset.

**Comment by Wuziyi616** [comment]
This may be a little bit complex. You need to modify the scripts provided by ONet repo. I will upload my modified scripts to this repo. I think you can compare them and make your own modifications to fit in with your settings.

Another thing I need to mention is, the generated point clouds have a different orientation (seem to be z-axis up) compared with the commonly used ModelNet40 sampled point clouds (seem to be y-axis up). You can change it by ```pointcloud=pointcloud[:, [0, 2, 1]]``` in data loading. I recommend you to visualize the point clouds and make sure they are aligned.

EDIT: I have uploaded them [here](https://github.com/Wuziyi616/IF-Defense/tree/main/ONet/data_proc). Take a look at them and feel free to ask me if you have any questions.

**Comment by paulwong16** [comment]
Hi @Wuziyi616 ,

Thanks for your kind reply.

I do try to convert meshes by Manifold, and I found that seems like .off files of bathtub category cannot be converted, did you discard them? 

trimesh reports that "NameError: Not an OFF file! Header was OFF3514 3546 0"

**Comment by paulwong16** [comment]
oops, I think it's just a small bug in those .off files, there should be an eol '\n' right after "OFF" in the header

**Comment by Wuziyi616** [comment]
> 
> 
> oops, I think it's just a small bug in those .off files, there should be an eol '\n' right after "OFF" in the header

Yes you are right. I am glad my answer helps :)
