### ISSUE TITLE
Could you send me the attack results of LG-GAN and AdvPC ?

### ISSUE THREAD

**Issue by cuge1995** [Wuziyi616/IF-Defense#3]
We want to test our method in defend LG-GAN and AdvPC, but they are written in TF, it is hard to implement them.

If you are willing to provide them, we will be very grateful.

My email is `228434973@qq.com`

**Comment by Wuziyi616** [comment]
I use the tf code for generating LG-GAN and AdvPC and there are small difference in the attack settings. For example, the orientation of point clouds used in their repo is z-axis up instead of y-axis up. So I think they may not be compatible to your experiments. But you can simply add dgcnn model to their tf code and generate adversarial examples using their code with little modifications. I think it is not very difficult. You can refer to the dgcnn implementation [here](https://github.com/WangYueFt/dgcnn/tree/master/tensorflow).

**Comment by cuge1995** [comment]
Thanks
